include $(GNUSTEP_MAKEFILES)/common.make

TOOL_NAME = weather

weather_OBJC_FILES = \
	main.m \
	WeatherData.m \
	WeatherService.m

weather_OBJC_LIBS = -lgnustep-base

include $(GNUSTEP_MAKEFILES)/tool.make
